### ISSUE TITLE
Graph is not being initialized properly during pulling new version 

### ISSUE THREAD

**Issue by yupbank** [tensorflow/serving#1027]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow Serving installed from (source or binary)**:
- **TensorFlow Serving version**:

### Describe the problem
The model version loading is not thread safe, somehow when we hit the request hard and new version of model would not get initialized properly 

```
{ "error": "Attempting to use uninitialized value linear/linear_model/bias_weights/part_0\n\t [[Node: linear/linear_model/bias_weights/part_0/read = Identity[T=DT_FLOAT, _output_shapes=[[10]], _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](linear/linear_model/bias_weights/part_0)]]" }
```

### Exact Steps to Reproduce
train and export a model with 

```
# deloy_new.py
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data


model_dir = "linear_fmnist_model"
model_base_path = "gs://tf-101-workshop/fashion_mnist"

dataset = input_data.read_data_sets('data/fashion', source_url='http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/')

feature_columns = [tf.feature_column.numeric_column("pixels", shape=[28, 28])]

classifier = tf.estimator.LinearClassifier(feature_columns=feature_columns,
                                                   n_classes=10,
 model_dir=model_dir,
)

train_input_fn = tf.estimator.inputs.numpy_input_fn(
    x={"pixels": dataset.train.images},
    y=dataset.train.labels.astype(tf.int32.as_numpy_dtype),
    num_epochs=None,
    batch_size=50,
    shuffle=True
)
classifier.train(input_fn=train_input_fn, steps=1000)


serving_input_func = tf.estimator.export.build_parsing_serving_input_receiver_fn(
                              {"pixels": tf.FixedLenFeature([28, 28], tf.float32)})

model_location = classifier.export_savedmodel(model_base_path, serving_input_func)
print(model_location)
```

deploy a model with app.yaml

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: models
  labels:
    name: models
    app: "fmnist"
data:
  config_list: |-
    model_config_list: {
      config: {
        name: "fmnist",
        base_path: "gs://tf-101-workshop/fashion_mnist/",
        model_platform: "tensorflow",
        model_version_policy: { all: {} }
      },
    }
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: fmnist
  name: fmnist
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: fmnist
    spec:
      containers:
      - args: ["/usr/bin/tensorflow_model_server", "--model_config_file=/app/models.prototxt", "--rest_api_port=9500"]
        name: model-server
        image: yupbank/tf_server:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /app
            name: model-config
        ports:
        - containerPort: 9500
      volumes:
      - name: model-config
        configMap:
          name: models
          items:
            - key: config_list
              path: models.prototxt
---
kind: Service
apiVersion: v1
metadata:
  name: fmnist-service
spec:
  selector:
    app: fmnist
  ports:
  - name: native-rest
    protocol: TCP
    port: 9500
    targetPort: 9500
  type: LoadBalancer
```

query the api with 
```
# query.py
import requests
import json

endpoint = 'http://the_ip_of_load_balancer:8888/model/fmnist/version/1533057754:classify'
res = requests.post(endpoint, data=json.dumps({'instances': [{'pixels':data}]}))
print res.text

```
try run the `deloy_new.py` again and call `query.py` a lot. there is a 50% of chance to have uninitialized error, and if any new versions of model get deployed after would be uninitialized

### Source code / logs
ever since there is this line of error

```
142 2018-07-31 17:30:47.689485: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:171] The specified SavedModel has no variables; no checkpoints were restored.
```
the rest new version would always end up with the same extra line.
