### ISSUE TITLE
TF Serving cannot handle more than 350 req/sec

### ISSUE THREAD

**Issue by roshanzameer** [tensorflow/serving#1517]
- Docker Image: Tensorflow/Serving:latest,
- Model: Fashion_Mnist (per the official Docs),
- Docker Version: 19.03.2, build 6a30dfc
- TensorFlow ModelServer: 2.0.0+dev.sha.b5a11f1
- TensorFlow Library: 2.0.0

I'm using Docker Container to serve a Tensorflow SavedModel over the REST API Port 8501. The inference latency is 2ms which is great.

Problem: I'm trying to perform load-testing and notice that the rate of requests stay constant at approximately 350 requests/sec. Beyond which the request fails. Every request has a single batch payload.

Observation: At the point of failure, the resource usage is just 10%. Server throws error code 404 and 401.

Troubleshooting:

1. Have tried running `tensorflow_model_server` directly instead of the docker image. Also used the `--rest_api_num_threads` argument. Same issue persists.
2. Have served different models (deep_mnist, custom models). Same issue persists.
3. Built a docker image with suitable instruction set. Same issue persists.
4. Deployed the Docker image on a K8 cluster. Set 4 Replicas behind a Loadbalancer. The pods resource usage is only 9% Same issue persists.
5. Pulled different tensorflow/serving image. Same issue persists.

What have I been doing wrong?

**Comment by RahulKulhari** [comment]
any update on this ?

**Comment by nrobeR** [comment]
Do you have the sample requests that you used for load testing? Also, if you could list the concrete steps (or even better in a script) to reproduce this issue that would be great. Thanks.

**Comment by roshanzameer** [comment]
@nrobeR 

**DOCKER:**

`docker run -it -p 8501:8501 -v "$(pwd)/mnist-model:/models/mnist-model" -e MODEL_NAME=mnist-model tensorflow/serving:latest --tensorflow_intra_op_parallelism=4 --tensorflow_inter_op_parallelism=4 --enable_batching=true --batching_parameters_file=/models/mnist-model/batch.conf`

Batching Config:

> num_batch_threads { value: 4 }
> batch_timeout_micros { value: 0}
> max_batch_size {value: 10000000}
> max_enqueued_batches {value: 4}

Request (Using Locust Loadtest framework):
```
from locust import HttpLocust, TaskSet, task, events, between
import json
import requests
import time
import numpy as np

class MnistLocust(TaskSet):

    @task
    def getPrediction(self):
        ndarr = np.random.rand(1,784)
        data = {"signature_name": "predict_images", "instances": ndarr.tolist()}
        headers = {"content-type": "application/json"}
        response = self.client.request("POST", 'http://localhost:8501/v1/models/mnist-model:predict', data=json.dumps(data), headers=headers)
        print(response.status_code)
        resp = json.loads(response.content)

class WebsiteUser(HttpLocust):
    task_set = MnistLocust
    wait_time = between(0.4, 0.9)
    stop_timeout = 10000000 # Stopping time

```

**KUBERNETES**

Cluster Info:
Nodes: 2
Memory: 32 Gb
CPU: 16 cores

Deployment YAML:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mnist-deployment
  namespace: mnist
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: mnist-server
    spec:
      containers:
      - name: mnist-container
        image: rossi619/tfserving-mnist:0.3             #Private repo image which has the SavedModel loaded
        ports:
          - containerPort: 8501
        resources:
          limits:
            cpu: 4
            memory: 8Gi
          requests:
            cpu: 3
            memory: 6Gi
        securityContext:
          runAsUser: 0
      terminationGracePeriodSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  namespace: mnist
  labels:
    run: mnist-service
  name: mnist-service
spec:
  ports:
  - port: 8501
    targetPort: 8501
  selector:
    app: mnist-server
  type: LoadBalancer
```
Replicas: 3
Max Request Rate via Loadbalancer: 402 req/sec
All Cluster Resource usage at failure: **10%**
