### ISSUE TITLE
`--rest_api_port` doesn´t enable HTTP server using metrics monitoring with Prometheus.

### ISSUE THREAD

**Issue by hampusrosvall** [tensorflow/serving#1863]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **TensorFlow Serving installed from (source or binary)**: tensorflow/serving Docker image
- **TensorFlow Serving version**: 2.5.1

### Describe the problem
I am looking into the new monitoring feature using a Prometheus server.

When I set the `--monitoring_config_file` I need to enable the HTTP server by setting the flag `--rest_api_port`. However, the HTTP server doesn't expose the REST API port when the `--monitoring_config_file` flag is passed. Omitting the monitoring flag, the HTTP server is exposed to the `--rest_api_port` port.

### Exact Steps to Reproduce
Including the flag:
```yaml
tfx:
        image: tensorflow/serving:2.5.1
        runtime: nvidia
        network_mode: host
        volumes:
            - /path/to/model:/models
        environment:
            - MODEL_NAME=<name_of_model>
        command: [--rest_api_port=8501, --monitoring_config_file=monitoring.config]
```
Excluding the flag:
```yaml
tfx:
        image: tensorflow/serving:2.5.1
        runtime: nvidia
        network_mode: host
        volumes:
            - /path/to/model:/models
        environment:
            - MODEL_NAME=<name_of_model>
        command: [--rest_api_port=8501]
```
### Source code / logs
Logs when `--monitoring_config_file` flag is provided:
```
...
tfx_1         | 2021-05-21 11:50:21.618675: I tensorflow_serving/model_servers/server.cc:367] Profiler service is enabled
tfx_1         | 2021-05-21 11:50:21.619077: I tensorflow_serving/model_servers/server.cc:393] Running gRPC ModelServer at 0.0.0.0:8500 ...
```

Logs when `--monitoring_config_file` flag is not provided:
```
tfx_1         | 2021-05-21 11:59:35.043282: I tensorflow_serving/model_servers/server.cc:367] Profiler service is enabled
tfx_1         | 2021-05-21 11:59:35.043649: I tensorflow_serving/model_servers/server.cc:393] Running gRPC ModelServer at 0.0.0.0:8500 ...
tfx_1         | 2021-05-21 11:59:35.045004: I tensorflow_serving/model_servers/server.cc:414] Exporting HTTP/REST API at:localhost:8501 ...
```

`monitoring.config`:
```config
prometheus_config {
  enable: true,
  path: "/monitoring/prometheus/metrics"
}
```
