### ISSUE TITLE
Reshape layer throws std::bad_alloc

### ISSUE THREAD

**Issue by Saoqq** [tensorflow/serving#2048]
### System information
-  OS: 
   *  Windows 11, 21H2, build 22000.856
   *  WSL2, Ubuntu 22.04 -- allocated 8Gb in .wslconfig
- TF Serving installed using docker, version 2.9.1
- Hardware:
  * AMD Ryzen 5 3600
  * RAM 16Gb

### Describe the problem
I'm facing issue with Reshape layer in TF serving 2.9.1.
It throws following to docker logs.

```
pythonproject-serving-1  | 2022-09-01 21:07:16.379819: I tensorflow_serving/model_servers/server.cc:442] Exporting HTTP/REST API at:localhost:8501 ...
pythonproject-serving-1  | [evhttp_server.cc : 245] NET_LOG: Entering the event loop ...
pythonproject-serving-1  | terminate called after throwing an instance of 'std::bad_alloc'
pythonproject-serving-1  |   what():  std::bad_alloc
pythonproject-serving-1  | /usr/bin/tf_serving_entrypoint.sh: line 3:     7 Aborted                 tensorflow_model_server --port=8500 --rest_api_port=8501 --model_name=${MODEL_NAME} --model_base_path=${MODEL_BASE_PATH}/${MODEL_NAME} "$@"
```

Also tried rolling back to older versions: the same mock model `WORKS ON TF SERVING 2.8.2`

### Exact Steps to Reproduce

Mock model to demonstrate issue, TF is 2.9.1
```pyhton
import numpy as np
import tensorflow as tf

model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(128, 64, 3)),
    tf.keras.layers.Reshape((12, 2048))
])

model.compile()

# ensure it works both on WSL and Windows
model.predict([np.ones(shape=(128, 64, 3)).tolist()])

model.save("./.data/models/v2_96acc/5")
```
Then serving with docker-compose with following config:
```
version: "3.8"
  serving:
    image: tensorflow/serving:2.9.1
    restart: on-failure
    ports:
      - "8501:8501"
    volumes:
      - "./.data/models:/models"
    environment:
      MODEL_NAME: v2_96acc
```

And evaluating results
```
import json
import numpy as np
import requests

image = {
    "inputs": [np.ones(shape=(128, 64, 3)).tolist()]
}

res = requests.post('http://localhost:8501/v1/models/v2_96acc/versions/5:predict', data=json.dumps(image))

print(len(res.json()['outputs']))
```

**Comment by aamontree** [comment]
I'm encountering the same error when sending prediction requests to the [universal-sentence-encoder-multilingual](https://tfhub.dev/google/universal-sentence-encoder-multilingual/3) model running on Docker container image `tensorflow/serving:2.9.1`.

**Comment by singhniraj08** [comment]
This error implies you are running out of memory or in other case a process is allocated a large memory portion that some is left unoccupied and cannot be used by another process. 

@Saoqq  & @aamontree, Kindly share the complete error stack trace for debugging the issue.

**Comment by aamontree** [comment]
In my case the container is running in a Kubernetes cluster within Google Cloud Platform. Here is what my deployment manifest looks like:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorflow-serving
  namespace: default
  labels:
    app: search-viewed-realtime
    tier: backend
  annotations:
    strategy.spinnaker.io/use-source-capacity: 'true'
spec:
  selector:
    matchLabels:
      app: search-viewed-realtime
      tier: backend
  template:
    metadata:
      labels:
        app: search-viewed-realtime
        tier: backend
    spec:
      containers:
        - name: tensorflow-serving
          image: 'tensorflow/serving:${version}'
          env:
            - name: MODEL_NAME
              value: 'universal-sentence-encoder-multilingual'
          resources:
            limits:
              cpu: 2.0
              memory: 1.0Gi
          ports:
            - containerPort: 8501
          volumeMounts:
            - name: model-storage
              mountPath: /models/
              readOnly: True
      volumes:
        - name: model-storage
          hostPath:
            path: /tmp/files/models/
```

I have tried increasing the memory allocation to `2.0Gi` and that did not fix the issue either.

Here are the full startup logs and error stacktrace:

```
I tensorflow_serving/model_servers/server.cc:89] Building single TensorFlow model file config:  model_name: universal-sentence-encoder-multilingual model_base_path: /models/universal-sentence-encoder-multilingual
I tensorflow_serving/model_servers/server_core.cc:465] Adding/updating models.
I tensorflow_serving/model_servers/server_core.cc:594] (Re-)adding model: universal-sentence-encoder-multilingual
I tensorflow_serving/core/basic_manager.cc:740] Successfully reserved resources to load servable {name: universal-sentence-encoder-multilingual version: 3}
I tensorflow_serving/core/loader_harness.cc:66] Approving load for servable version {name: universal-sentence-encoder-multilingual version: 3}
I tensorflow_serving/core/loader_harness.cc:74] Loading servable version {name: universal-sentence-encoder-multilingual version: 3}
I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:43] Reading SavedModel from: /models/universal-sentence-encoder-multilingual/3
I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:81] Reading meta graph with tags { serve }
I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:122] Reading SavedModel debug info (if present) from: /models/universal-sentence-encoder-multilingual/3
I external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
I external/org_tensorflow/tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:354] MLIR V1 optimization pass is not enabled
I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:228] Restoring SavedModel bundle.
I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:212] Running initialization op on SavedModel bundle at path: /models/universal-sentence-encoder-multilingual/3I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:301] SavedModel load for tags { serve }; Status: success: OK. Took 2499582 microseconds.
I tensorflow_serving/servables/tensorflow/saved_model_warmup_util.cc:71] Starting to read warmup data for model at /models/universal-sentence-encoder-multilingual/3/assets.extra/tf_serving_warmup_requests with model-warmup-options 
terminate called after throwing an instance of 'std::bad_alloc'
what(): std::bad_alloc
/usr/bin/tf_serving_entrypoint.sh: line 3:     7 Aborted                 (core dumped) tensorflow_model_server --port=8500 --rest_api_port=8501 --model_name=${MODEL_NAME} --model_base_path=${MODEL_BASE_PATH}/${MODEL_NAME} "$@"
```

I am using [SavedModel Warmup](https://www.tensorflow.org/tfx/serving/saved_model_warmup) to send prediction requests to the model on startup so this error is causing the pod to repeatedly crash and restart.
